
version: "3"

services:
  admin:
    image: "tomcat:8.5-alpine"
    # ports:
    #   - "30000:8080"
    volumes:
      - /Users/IT/code/vehicle-admin/target/vehicle-admin.war:/usr/local/tomcat/webapps/ROOT.war
    command: sh -c "rm -rf /usr/local/tomcat/webapps/ROOT && catalina.sh run"
    networks:
      - app-net
      
  push:
    image: "tomcat:8.5-alpine"
    # ports:
    #   - "30001:8080"
    volumes:
      - /Users/IT/code/vehicle-push/target/vehicle-push.war:/usr/local/tomcat/webapps/ROOT.war
    entrypoint:
      - sh
      - -c
      - "rm -rf /usr/local/tomcat/webapps/ROOT && catalina.sh run"
    networks:
      - app-net

  web:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net
      
networks:
  app-net:
